meta:
  name: split_6x5_with_thumbs
  version: 1.0
  author: jost

units:
  px: cx + 2
  py: cy + 2

  pushX: (cx / 2)
  pushY: (cy / 2)

  padX: pushX + 2
  padY: pushY + 2

  pad: 2

  spacing: 0.75

  caseBorder: 1.5

  u: 19

points:
  zones:
    matrix:
      anchor:
        shift: [0, 0]   # po potrebi spremeni, da lepo centruješ
      columns:
        first:
          key:
            stagger: 0
            column_net: P10
        second:
          key:
            stagger: 0
            column_net: P16
        third:
          key:
            stagger: 7
            column_net: P14
        fourth:
          key:
            stagger: 5
            column_net: P15
        fifth:
          key:
            stagger: -6
            column_net: P18
        sixth:
          key:
            stagger: -3
            column_net: P19
      rows:
        mod:
          row_net: P2
        bottom:
          row_net: P3
        home:
          row_net: P4
        top:
          row_net: P5
        num:
          row_net: P6

    thumbs:
      anchor:
        ref: matrix_sixth_mod   # začetek thumb clusterja
        shift: [0.25u, -1.15u]
      columns:
        t1:
          key:
            splay: -20
            spread: u
            column_net: P18
          rows:
            thumb: {row_net: P7}
        t2:
          key:
            spread: u
            shift: [0, -0.1u]
            column_net: P19
          rows:
            thumb: {row_net: P7}

  mirror:
    ref: matrix_third_home
    distance: 10u

outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        # Top
      - ref: matrix_first_num
        shift: [-padX, padY]
      - ref: matrix_second_num
        shift: [pushX - pad, padY]
      - ref: matrix_third_num
        shift: [-pushX - pad, padY]
      - ref: matrix_third_num
        shift: [pushX - pad, padY]
      - ref: matrix_fourth_num
        shift: [-pushX - pad, padY]
      - ref: matrix_fourth_num
        shift: [padX, padY]
      - ref: matrix_fifth_num
        shift: [-pushX + pad, padY]
      - ref: matrix_fifth_num
        shift: [padX, padY]
      - ref: matrix_sixth_num
        shift: [-pushX + 2.3542486, padY]
      - ref: matrix_sixth_num
        shift: [padX, padY]

      # Spremenjeno ker more it do sredine thumbou
      - ref: matrix_sixth_mod
        shift: [padX, -padY]

      - ref: thumbs_t1_thumb
        shift: [0.25padX, padY]
      - ref: thumbs_t1_thumb
        shift: [padX, padY]
      - ref: thumbs_t2_thumb
        shift: [-pushX + 1.6pad, padY]
      - ref: thumbs_t2_thumb
        shift: [padX, padY]
      - ref: thumbs_t2_thumb
        shift: [padX, -padY]
      - ref: thumbs_t2_thumb
        shift: [-padX, -padY]
      - ref: thumbs_t1_thumb
        shift: [pushX - 1.6pad, -padY]
      - ref: thumbs_t1_thumb
        shift: [-padX, -padY]
      - ref: thumbs_t1_thumb
        shift: [-padX, 0.4pushY]
      

      - ref: matrix_sixth_mod
        shift: [-pushX, -padY]
      - ref: matrix_fifth_mod
        shift: [pushX - pad, -padY]
      - ref: matrix_fifth_mod
        shift: [-padX, -padY]
      - ref: matrix_fourth_mod
        shift: [pushX - pad, -padY]
      - ref: matrix_fourth_mod
        shift: [-pushX + pad, -padY]
      - ref: matrix_third_mod
        shift: [pushX + pad, -padY]
      - ref: matrix_third_mod
        shift: [-pushX + pad, -padY]
      - ref: matrix_second_mod
        shift: [pushX + pad, -padY]
      - ref: matrix_second_mod
        shift: [-pushX + pad, -padY]
      - ref: matrix_first_mod
        shift: [-padX, -padY]

      # - ref: thumbs_t1_thumb
      #   shift: [-padX, -padY - 0.5u]   # levi thumb, nekoliko nižje
      # - ref: thumbs_t2_thumb
      #   shift: [padX, -padY - 0.7u]  

      # Connect to top
      - ref: matrix_first_num
        shift: [-padX, -padY]

  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        # Top
        - ref: mirror_matrix_first_num
          shift: [-padX, padY]
        - ref: mirror_matrix_second_num
          shift: [pushX - pad, padY]
        - ref: mirror_matrix_third_num
          shift: [-pushX - pad, padY]
        - ref: mirror_matrix_third_num
          shift: [pushX - pad, padY]
        - ref: mirror_matrix_fourth_num
          shift: [-pushX - pad, padY]
        - ref: mirror_matrix_fourth_num
          shift: [padX, padY]
        - ref: mirror_matrix_fifth_num
          shift: [-pushX + pad, padY]
        - ref: mirror_matrix_fifth_num
          shift: [padX, padY]
        - ref: mirror_matrix_sixth_num
          # Won't fillet unless small num added. Bug?
          shift: [-pushX + pad + 0.001, padY]
        - ref: mirror_matrix_sixth_num
          shift: [padX, padY]
        # Bottom
        - ref: mirror_matrix_sixth_mod
          shift: [padX, -padY]
        
        # Thumbs
        - ref: mirror_thumbs_t1_thumb
          shift: [0.25padX, padY]
        - ref: mirror_thumbs_t1_thumb
          shift: [padX, padY]
        - ref: mirror_thumbs_t2_thumb
          shift: [-pushX + 1.6pad, padY]
        - ref: mirror_thumbs_t2_thumb
          shift: [padX, padY]
        - ref: mirror_thumbs_t2_thumb
          shift: [padX, -padY]
        - ref: mirror_thumbs_t2_thumb
          shift: [-padX, -padY]
        - ref: mirror_thumbs_t1_thumb
          shift: [pushX - 1.6pad, -padY]
        - ref: mirror_thumbs_t1_thumb
          shift: [-padX, -padY]
        - ref: mirror_thumbs_t1_thumb
          shift: [-padX, 0.4pushY]
        
        - ref: mirror_matrix_sixth_mod
          shift: [-pushX, -padY]
        - ref: mirror_matrix_fifth_mod
          shift: [pushX - pad, -padY]
        - ref: mirror_matrix_fifth_mod
          shift: [-padX, -padY]
        - ref: mirror_matrix_fourth_mod
          shift: [pushX - pad, -padY]
        - ref: mirror_matrix_fourth_mod
          shift: [-pushX + pad, -padY]
        - ref: mirror_matrix_third_mod
          shift: [pushX + pad, -padY]
        - ref: mirror_matrix_third_mod
          shift: [-pushX + pad, -padY]
        - ref: mirror_matrix_second_mod
          shift: [pushX + pad, -padY]
        - ref: mirror_matrix_second_mod
          shift: [-pushX + pad, -padY]
        - ref: mirror_matrix_first_mod
          shift: [-padX, -padY]

        # Connect to top
        - ref: mirror_matrix_first_num
          shift: [-padX, -padY]

pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap_matrix:
        what: choc
        where: /^matrix_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180

      choc_hotswap_thumbs:
        what: choc
        where: /^thumbs_.*/        # ujame tipke v thumbs zoni
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      
      diode_main:
        what: diode
        where: /^matrix_(?!(?:sixth_top|sixth_home|third_home|first_num|first_bottom|fourth_top|fourth_mod)).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90

      # Special matrix diodes to avoid controller conflicts
      diode_weird1:
        what: diode
        where: matrix_sixth_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -16.0]
          rotate: 90

      diode_weird2:
        what: diode
        where: matrix_sixth_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -9.5]
          rotate: 90

      # Matrix diodes that conflict with mounting holes
      diode_mounting_hole_conflict1:
        what: diode
        where: /^matrix_(?:third_home|first_num|first_bottom)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, 3.5]
          rotate: 90

      diode_mounting_hole_conflict2:
        what: diode
        where: /^matrix_(?:fourth_top|fourth_mod)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -4.5]
          rotate: 90

      # Thumbs diodes (extra, since thumbs are outside matrix)
      diode_thumbs:
        what: diode
        where: /^thumbs_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]   # isto kot pri main
          rotate: 90

      # Pro Micro
      controller:
        what: promicro
        params:
          orientation: "down"       # lahko: up, down, left, right (kako obrneš footprint)
        where:
          ref: matrix_sixth_num   # glede na katero tipko ga pozicioniraš
          shift: [-9, -1.5]       # pomik X, Y v mm (ali v u, če dodaš enoto)
          rotate: -180.0 

      trrs:
        what: trrs
        where:
          ref: matrix_sixth_top
          shift: [padX-1.4pad, pushY/2 - 0.7pad]
          rotate: -90
        params:
          A: GND
          B: GND
          C: P21
          D: VCC
          reverse: true
          symmetric: true

      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: matrix_fifth_mod
          shift: [-pushX, pushY]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: matrix_first_bottom
          shift: [pushX, -pushY]
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_second_num
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_fifth_top
          shift: [-pushX, pushY]
      hole_center:
        what: mountinghole
        where:
          ref: matrix_fourth_bottom
          shift: [-pushX, pushY]
      hole_thumbs:
        what: mountinghole
        where:
          ref: thumbs_t1_thumb
          shift: [-0.8pushX, 0.8pushY]

  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap_matrix:
        what: choc
        where: /^mirror_matrix_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180

      choc_hotswap_thumbs:
        what: choc
        where: /^mirror_thumbs_.*/        # ujame tipke v thumbs zoni
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      
      # Main diodes
      diode_main:
        what: diode
        where: /^mirror_matrix_(?!(?:fourth_home|second_bottom|second_num|fifth_bottom|fifth_num|sixth_num)).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, -3.5]
          rotate: 90

      # Move a diode so it doesn't conflict with mounting hole
      diode_mounting_hole_conflict:
        what: diode
        where: /^mirror_matrix_(?:fourth_home|second_bottom|second_num|fifth_bottom|fifth_num)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, 2.0]
          rotate: 90

      # Move a diode so it doesn't conflict with the controller
      diode_promicro_conflict:
        what: diode
        where: mirror_matrix_sixth_num
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, -1.0]
          rotate: 90

      # Thumbs diodes (extra, since thumbs are outside matrix)
      diode_thumbs:
        what: diode
        where: /^mirror_thumbs_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, -3.5]   # isto kot pri main
          rotate: 90

      # Pro Micro
      controller:
        what: promicro
        params:
          orientation: "down"         # lahko: up, down, left, right (kako obrneš footprint)
        where:
          ref: mirror_matrix_sixth_num   # glede na katero tipko ga pozicioniraš
          shift: [-9, -1.5]       # pomik X, Y v mm (ali v u, če dodaš enoto)

      trrs:
        what: trrs
        where:
          ref: mirror_matrix_sixth_top
          shift: [padX-1.4pad, pushY - 0.5pad]
          rotate: -90
        params:
          A: GND
          B: GND
          C: P21
          D: VCC
          reverse: true
          symmetric: true
      
      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_matrix_fifth_mod
          shift: [-pushX, pushY]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_matrix_first_bottom
          shift: [pushX, -pushY]
      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_matrix_second_num
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_matrix_fifth_top
          shift: [-pushX, pushY]
      hole_center:
        what: mountinghole
        where:
          ref: mirror_matrix_third_bottom
          shift: [pushX, pushY]
      hole_thumbs:
        what: mountinghole
        where:
          ref: mirror_thumbs_t1_thumb
          shift: [-0.8pushX, 0.8pushY]
